### ISSUE TITLE
Thoughts on v0.2

### ISSUE THREAD

**Issue by nikklassen** [erinvaa/league-of-legends-magic-cards#1]
- [ ] Aatrox: I don't understand the flavour of the last ability
- [x] "Alistar, Minotaur" seems a little unnecessary given his sub-type is minotaur
- [x] Anivia: "transform Egg" should be "transform Egg of the Cryopheonix"
- [x] Cho'Gath: Love him, no comment
- [x] Evelynn: Ability seems to cost a lot
- [ ] Fiddlesticks: Could be neat to have an ability like "Target creature gets -1/-1 and Fiddlesticks gets +1/+1 until end of turn", but that might be too many abilities
- [x] Gnar: A bit underwhelming for the cost to transform him
- [x] Gragas: Grammar (Each creature deals).
- [ ] Irelia: Justification counter.  Jusitified refers to the counter itself, justification is what the counter provides.
- [ ] Jhin: Possibly 1BR, since Jinx and him and pretty comparable and the 4 charge counters is definitely worth the cost of the destroy ability.
- [ ] Kennen: Any other cards with Ninjustu / the ninja creature type are U/B.  Not saying you have to change him, but I don't think the ability flavour works with your colour choices.
- [x] Kindred: Doesn't seem like a very helpful card except against pretty specific decks (unlike the colour/creature type abilities which I think are general enough)
- [x] Lissandra: Also underwhelming
- [ ] Lux: Seems like a huge advantage of 1W
- [x] Nasus: He's neat, I like him
- [x] Orianna: Should "The Ball" be legendary?
- [x] Poppy: "consider**ed**"
- [x] Renekton: "his power" arguably refers to the player's power.  Should be Renekton's power or possibly, "Renekton gains first strike until end of turn and causes target player to lose life equal to his power" although that might still have the same problem.

More to come

*Note: I don't know a lot about mana balancing so feel free to ignore all suggestions on that topic

**Comment by erinvaa** [comment]
Checked items were dealt with easily (some were redesigned).

Aatrox: His character matches very well to the idea of forcing creatures to attack. Unfortunately his gameplay doesn't match that super well. I think that's fine for now anyway.
Evelynn: Now costs 1 less and activates as sorcery. FYI, the reason it costs so much is because repeated kill spells are **very** good.
Fiddlesticks: Ya, definately a good idea, but I don't know that it added enough to the card to be worth the space. Don't think so currently, but I'll write it down in the file.
Gnar: Ya... I've got lots of similar feedback for Gnar. I've added R, T: Deal 1 damage to small Gnar, and creatures you control get +2/+2 and trample until end of turn for Mega Gnar. We'll see if that's enough.
Irelia: While I appreciate your ability to be precise, I'm not convinced that it reads better that way. I'll run it by some people, see if anyone says anything.
Jhin: He's gone through a bit of a redesign, OT and Cam both said he was too hard to pull off, so I'm trying something new.
Kennen: Ya, he's another card that needs a redesign. While I could do without the Ninjistu, I don't think the UB-ness of it previously is enough to cut it on it's own. Color-pie-wise, it's not breaking anything.
Lux: I think it's okay, but I could be wrong. I'll run it by some of my more power-level focused people. Might get bumped up to 2W or possibly WW.

Thanks for the feedback :) Looking forward for you to go over the next half :P
